# Generated by Django 4.1.2 on 2022-10-23 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
                ('question', models.TextField(blank=True, max_length=1000)),
                ('time_to_public', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('AWAITING_ANSWER', 'AWAITING_ANSWER'), ('ANSWERED', 'ANSWERED')], default='AWAITING_ANSWER', max_length=200)),
                ('from_user', models.ForeignKey(blank=True, on_delete=django.db.models.fields.NOT_PROVIDED, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, on_delete=django.db.models.fields.NOT_PROVIDED, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
