# Generated by Django 4.1.2 on 2022-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_user', models.CharField(default='', max_length=15)),
                ('Subject', models.CharField(max_length=120)),
                ('Teacher', models.CharField(max_length=120)),
                ('type_of_week', models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная'), ('Еженедельно', 'Еженедельно')], default=('Еженедельно', 'Еженедельно'), max_length=20)),
                ('day_of_week', models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default=('2Вторник', 'Вторник'), max_length=20)),
                ('serial_number_of_lesson', models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая')], default=('2', 'Вторая'), max_length=1)),
                ('auditory', models.CharField(max_length=10)),
            ],
        ),
    ]
