# Generated by Django 4.1.2 on 2022-10-22 20:56

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, null=True)),
                ('teacher', models.CharField(max_length=120, null=True)),
                ('day_of_week', models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default='1Понедельник', max_length=25)),
                ('serial_number_of_lesson', models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая')], default='1', max_length=1)),
                ('auditory', models.CharField(max_length=10, null=True)),
                ('group_user', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='student_group.studentgroup')),
            ],
        ),
    ]
