# Generated by Django 4.1.2 on 2022-10-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Group_user',
            new_name='group_user',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
