# Generated by Django 4.1.2 on 2022-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_group_user_schedule_group_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='excel',
            field=models.FileField(default='', upload_to='excels/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='auditory',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
