# Generated by Django 4.1.2 on 2022-10-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_excel_alter_schedule_auditory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default=('1Понедельник', 'Понедельник'), max_length=25),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type_of_week',
            field=models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная'), ('Еженедельно', 'Еженедельно')], default=('Еженедельно', 'Еженедельно'), max_length=25),
        ),
    ]
