# Generated by Django 4.1.2 on 2022-10-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default='1Понедельник', max_length=25),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='serial_number_of_lesson',
            field=models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая')], default='1', max_length=1),
        ),
    ]
