# Generated by Django 4.1.2 on 2022-10-23 08:14

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student_group', '0001_initial'),
        ('schedule', '0005_alter_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group_user',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='student_group.studentgroup'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type_of_week',
            field=models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная'), ('Еженедельно', 'Еженедельно')], default='Четная', max_length=25),
        ),
    ]
