# Generated by Django 4.1.2 on 2022-10-21 20:54

from django.db import migrations
from ..group_creation import create_groups


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_groups)]
