# Generated by Django 4.1.2 on 2022-10-23 08:14

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student_group', '0001_initial'),
        ('users', '0003_user_edu_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edu_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.fields.NOT_PROVIDED, to='student_group.studentgroup'),
        ),
    ]
