# Generated by Django 4.1.2 on 2022-10-22 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('short_desc', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=800)),
                ('img', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date_posted', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('hashtag', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
