# Generated by Django 4.1.2 on 2022-10-22 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hashtag',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
